// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabibPlus.Infrastructure.Data;

#nullable disable

namespace TabibPlus.Infrastructure.Migrations
{
    [DbContext(typeof(TabibPlusDbContext))]
    [Migration("20260719131250_AddNomPrenomToUser")]
    partial class AddNomPrenomToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TabibPlus.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntiteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DateHeure");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Avis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAvis")
                        .HasColumnType("datetime2");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PraticienId")
                        .HasColumnType("int");

                    b.Property<int>("RendezVousId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PraticienId");

                    b.HasIndex("RendezVousId")
                        .IsUnique();

                    b.ToTable("Avis");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Cabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abonnement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AbonnementExpire")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AccesHandicap")
                        .HasColumnType("bit");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorairesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroConvention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Parking")
                        .HasColumnType("bit");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VilleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VilleId");

                    b.ToTable("Cabinets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abonnement = "Premium",
                            AccesHandicap = false,
                            Adresse = "123 Avenue Mohammed V",
                            CreeLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Cabinet Test TabibPlus",
                            Parking = false,
                            Telephone = "0522000000",
                            Type = "Solo",
                            VilleId = 1
                        });
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinataireId")
                        .HasColumnType("int");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("int");

                    b.Property<bool>("Lu")
                        .HasColumnType("bit");

                    b.Property<string>("PieceJointeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Antecedents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConsentementDonne")
                        .HasColumnType("bit");

                    b.Property<string>("ContactUrgenceNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactUrgenceTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateConsentement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupeSanguin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medicaments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroAssurance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Poids")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Taille")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TypeAssurance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Telephone");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.PhotoCabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<int>("PraticienId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PraticienId");

                    b.ToTable("PhotosCabinet");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.PlageHoraire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("JourSemaine")
                        .HasColumnType("int");

                    b.Property<int>("PraticienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PraticienId");

                    b.ToTable("PlagesHoraires");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Praticien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccepteNouveauxPatients")
                        .HasColumnType("bit");

                    b.Property<bool>("AccepteTeleconsult")
                        .HasColumnType("bit");

                    b.Property<int>("AnneesExperience")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CabinetId")
                        .HasColumnType("int");

                    b.Property<string>("Diplomes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DureeRdvDefaut")
                        .HasColumnType("int");

                    b.Property<decimal>("Honoraires")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Inpe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Langues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreAvis")
                        .HasColumnType("int");

                    b.Property<decimal>("NoteMoyenne")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("PhotoProfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProfilValide")
                        .HasColumnType("bit");

                    b.Property<string>("Secteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecialiteId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VilleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("SpecialiteId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VilleId");

                    b.ToTable("Praticiens");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Rappel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePrevue")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Envoye")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EnvoyeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Erreur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RendezVousId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RendezVousId");

                    b.ToTable("Rappels");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.RendezVous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvisLaisse")
                        .HasColumnType("bit");

                    b.Property<int>("CabinetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("EstTeleconsultation")
                        .HasColumnType("bit");

                    b.Property<string>("LienVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontantHonoraires")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesConsultation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ordonnance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PraticienId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirme");

                    b.Property<string>("StatutPaiement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("PatientId", "DateHeure");

                    b.HasIndex("PraticienId", "DateHeure");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Specialite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = "Médecine",
                            Icone = "🩺",
                            NomAr = "الطب العام",
                            NomFr = "Médecine générale"
                        },
                        new
                        {
                            Id = 2,
                            Categorie = "Médecine",
                            Icone = "❤️",
                            NomAr = "أمراض القلب",
                            NomFr = "Cardiologie"
                        },
                        new
                        {
                            Id = 3,
                            Categorie = "Médecine",
                            Icone = "🔬",
                            NomAr = "الجلدية",
                            NomFr = "Dermatologie"
                        },
                        new
                        {
                            Id = 4,
                            Categorie = "Médecine",
                            Icone = "👶",
                            NomAr = "أمراض النساء",
                            NomFr = "Gynécologie"
                        },
                        new
                        {
                            Id = 5,
                            Categorie = "Médecine",
                            Icone = "🧒",
                            NomAr = "طب الأطفال",
                            NomFr = "Pédiatrie"
                        },
                        new
                        {
                            Id = 6,
                            Categorie = "Médecine",
                            Icone = "👁️",
                            NomAr = "طب العيون",
                            NomFr = "Ophtalmologie"
                        },
                        new
                        {
                            Id = 7,
                            Categorie = "Dentaire",
                            Icone = "🦷",
                            NomAr = "طب الأسنان",
                            NomFr = "Dentiste"
                        },
                        new
                        {
                            Id = 8,
                            Categorie = "Médecine",
                            Icone = "🦴",
                            NomAr = "جراحة العظام",
                            NomFr = "Orthopédie"
                        },
                        new
                        {
                            Id = 9,
                            Categorie = "Mental",
                            Icone = "🧠",
                            NomAr = "الطب النفسي",
                            NomFr = "Psychiatrie"
                        },
                        new
                        {
                            Id = 10,
                            Categorie = "Paramédical",
                            Icone = "💪",
                            NomAr = "العلاج الطبيعي",
                            NomFr = "Kinésithérapie"
                        });
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<int?>("CabinetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationsEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificationsSms")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Secretaire");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCompte")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Patient");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Ville", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NomAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Villes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 33.573099999999997,
                            Longitude = -7.5898000000000003,
                            NomAr = "الدار البيضاء",
                            NomFr = "Casablanca",
                            Region = "Casablanca-Settat"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 34.020899999999997,
                            Longitude = -6.8415999999999997,
                            NomAr = "الرباط",
                            NomFr = "Rabat",
                            Region = "Rabat-Salé-Kénitra"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 31.6295,
                            Longitude = -7.9810999999999996,
                            NomAr = "مراكش",
                            NomFr = "Marrakech",
                            Region = "Marrakech-Safi"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 34.018099999999997,
                            Longitude = -5.0077999999999996,
                            NomAr = "فاس",
                            NomFr = "Fès",
                            Region = "Fès-Meknès"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 35.759500000000003,
                            Longitude = -5.8339999999999996,
                            NomAr = "طنجة",
                            NomFr = "Tanger",
                            Region = "Tanger-Tétouan-Al Hoceïma"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 30.427800000000001,
                            Longitude = -9.5981000000000005,
                            NomAr = "أكادير",
                            NomFr = "Agadir",
                            Region = "Souss-Massa"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 33.893500000000003,
                            Longitude = -5.5472999999999999,
                            NomAr = "مكناس",
                            NomFr = "Meknès",
                            Region = "Fès-Meknès"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 34.680500000000002,
                            Longitude = -1.9076,
                            NomAr = "وجدة",
                            NomFr = "Oujda",
                            Region = "Oriental"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 34.261000000000003,
                            Longitude = -6.5801999999999996,
                            NomAr = "القنيطرة",
                            NomFr = "Kénitra",
                            Region = "Rabat-Salé-Kénitra"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 35.578499999999998,
                            Longitude = -5.3684000000000003,
                            NomAr = "تطوان",
                            NomFr = "Tétouan",
                            Region = "Tanger-Tétouan-Al Hoceïma"
                        });
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Avis", b =>
                {
                    b.HasOne("TabibPlus.Core.Entities.Patient", "Patient")
                        .WithMany("Avis")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabibPlus.Core.Entities.Praticien", "Praticien")
                        .WithMany("Avis")
                        .HasForeignKey("PraticienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabibPlus.Core.Entities.RendezVous", "RendezVous")
                        .WithOne("Avis")
                        .HasForeignKey("TabibPlus.Core.Entities.Avis", "RendezVousId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Praticien");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Cabinet", b =>
                {
                    b.HasOne("TabibPlus.Core.Entities.Ville", "Ville")
                        .WithMany("Cabinets")
                        .HasForeignKey("VilleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ville");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.PhotoCabinet", b =>
                {
                    b.HasOne("TabibPlus.Core.Entities.Praticien", "Praticien")
                        .WithMany("Photos")
                        .HasForeignKey("PraticienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Praticien");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.PlageHoraire", b =>
                {
                    b.HasOne("TabibPlus.Core.Entities.Praticien", "Praticien")
                        .WithMany("PlagesHoraires")
                        .HasForeignKey("PraticienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Praticien");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Praticien", b =>
                {
                    b.HasOne("TabibPlus.Core.Entities.Cabinet", "Cabinet")
                        .WithMany("Praticiens")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabibPlus.Core.Entities.Specialite", "Specialite")
                        .WithMany("Praticiens")
                        .HasForeignKey("SpecialiteId");

                    b.HasOne("TabibPlus.Core.Entities.User", "User")
                        .WithOne("Praticien")
                        .HasForeignKey("TabibPlus.Core.Entities.Praticien", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabibPlus.Core.Entities.Ville", null)
                        .WithMany("Praticiens")
                        .HasForeignKey("VilleId");

                    b.Navigation("Cabinet");

                    b.Navigation("Specialite");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Rappel", b =>
                {
                    b.HasOne("TabibPlus.Core.Entities.RendezVous", "RendezVous")
                        .WithMany("Rappels")
                        .HasForeignKey("RendezVousId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.RendezVous", b =>
                {
                    b.HasOne("TabibPlus.Core.Entities.Cabinet", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TabibPlus.Core.Entities.Patient", "Patient")
                        .WithMany("RendezVous")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TabibPlus.Core.Entities.Praticien", "Praticien")
                        .WithMany("RendezVous")
                        .HasForeignKey("PraticienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Patient");

                    b.Navigation("Praticien");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.User", b =>
                {
                    b.HasOne("TabibPlus.Core.Entities.Cabinet", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Cabinet", b =>
                {
                    b.Navigation("Praticiens");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Patient", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Praticien", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Photos");

                    b.Navigation("PlagesHoraires");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.RendezVous", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Rappels");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Specialite", b =>
                {
                    b.Navigation("Praticiens");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.User", b =>
                {
                    b.Navigation("Praticien");
                });

            modelBuilder.Entity("TabibPlus.Core.Entities.Ville", b =>
                {
                    b.Navigation("Cabinets");

                    b.Navigation("Praticiens");
                });
#pragma warning restore 612, 618
        }
    }
}
